### ISSUE TITLE
Duplicate favorites

### ISSUE THREAD

**Issue by TheGlider0** [45026831/hh-plus-plus#93] opened 2023-01-19 19:33 UTC
Placing a star on a piece of equipment (favoriting) when there is a similar piece of equipment in the inventory marks both of them simultaneously (in this case, both pieces are of the same rarity, and the same name, but different in their resonance bonuses).

Script version is 1.28.24
browser is Chrome Version 109.0.5414.74

![Screenshot 2023-01-19 212511](https://user-images.githubusercontent.com/90114177/213542007-8b558e21-c7a6-42a7-b9f5-f2bd3d470809.png)
![Screenshot 2023-01-19 212530](https://user-images.githubusercontent.com/90114177/213542043-52f048fa-41ac-424f-9bf7-d23952128660.png)

**Comment by 45026831** [comment] 2023-01-20 17:25
Duplicate of #92

**Closed by 45026831** 2023-01-20 17:25 UTC
